baseURL = 'https://684abf78e034e029ed9140ec--aroundgo.netlify.app'
languageCode = 'en-us'
title = 'Around Go'
theme = "PaperMod"
[params]
DateFormat = '2006, January 2'
defaultTheme = 'dark'
disableThemeToggle = false
ShowReadingTime = true